version: "2"

services:
  nginx:
    build: ./nginx
    image: tuxxon/nginx
    env_file:
      - ./config.env
    volumes:
      - nginx_conf:/etc/nginx/sites
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
      - ./vhosts:/etc/nginx/vhosts
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    build: ./certbot
    image: tuxxon/certbot
    env_file:
      - ./config.env
    volumes:
      - letsencrypt_certs:/etc/letsencryptll
      - certbot_acme_challenge:/var/www/certbot

  cron:
    build: ./cron
    image: tuxxon/cron
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    restart: unless-stopped

# node-server:
#   build: ./packages/server
#   image: tuxxon/node-server
#   restart: "on-failure"
#   expose:
#     - 8080
#   volumes:
#     - './packages/server:/app'
#     - '/app/node_modules'
#   environment:
#     - NODE_ENV=development
#     - CHOKIDAR_USEPOLLING=true
#   stdin_open: true
#   tty: true

volumes:
  nginx_conf:
    external: true
  letsencrypt_certs:
    external: true
  certbot_acme_challenge:
